version: '3.8'

services:
  mongo:
    image: ${MONGO_IMAGE}
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - ${MONGO_PORTS}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:      