env: "prod"
server_config:
  listen_addr: "0.0.0.0:3000"
  read_timeout: 4s
  write_timeout: 8s
  idle_timeout: 60s
mongo_config:
  user: ""
  password: ""
  host: ""
  port: ""
  db_name: ""
  coll_name: ""
  auth_source: ""
